// SPDX-License-Identifier: BSD-3-Clause
/* Copyright (c) 2022, Linaro Limited */

#include <sys/mman.h>
#include <err.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "debugcc.h"

static struct gcc_mux gcc = {
	.mux = {
		.phys = 0xfc400000,
		.size = 0x2000,

		.measure = measure_gcc,

		.enable_reg = 0x1880,
		.enable_mask = BIT(16),

		.mux_reg = 0x1880,
		.mux_mask = 0x3ff,

		.div_reg = 0x1880,
		.div_shift = 12,
		.div_mask = 0xf << 12,
		.div_val = 4,
	},

	.xo_div4_reg = 0x10c8,
	.debug_ctl_reg = 0x1884,
	.debug_status_reg = 0x1888,
};

static struct debug_mux mmcc = {
	.phys = 0xfd8c0000,
	.size = 0x5200,
	.block_name = "mm",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x2b,

	.enable_reg = 0x900,
	.enable_mask = BIT(16),

	.mux_reg = 0x900,
	.mux_mask = 0x3ff,
};

static struct measure_clk msm8994_clocks[] = {
	// { "debug_cpu_clk", &gcc.mux, 0x16a },

	{ .name = "gcc_sys_noc_usb3_axi_clk", .clk_mux = &gcc.mux, .mux = 0x6 },
	{ .name = "gcc_mss_q6_bimc_axi_clk", .clk_mux = &gcc.mux, .mux = 0x31 },
	{ .name = "gcc_usb30_master_clk", .clk_mux = &gcc.mux, .mux = 0x50 },
	{ .name = "gcc_usb30_sleep_clk", .clk_mux = &gcc.mux, .mux = 0x51 },
	{ .name = "gcc_usb30_mock_utmi_clk", .clk_mux = &gcc.mux, .mux = 0x52 },
	{ .name = "gcc_usb3_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x53 },
	{ .name = "gcc_usb3_phy_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x54 },
	{ .name = "gcc_sys_noc_ufs_axi_clk", .clk_mux = &gcc.mux, .mux = 0x58 },
	{ .name = "gcc_usb_hs_system_clk", .clk_mux = &gcc.mux, .mux = 0x60 },
	{ .name = "gcc_usb_hs_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x61 },
	{ .name = "gcc_usb2_hs_phy_sleep_clk", .clk_mux = &gcc.mux, .mux = 0x63 },
	{ .name = "gcc_usb_phy_cfg_ahb2phy_clk", .clk_mux = &gcc.mux, .mux = 0x64 },
	{ .name = "gcc_sdcc1_apps_clk", .clk_mux = &gcc.mux, .mux = 0x68 },
	{ .name = "gcc_sdcc1_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x69 },
	{ .name = "gcc_sdcc2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x70 },
	{ .name = "gcc_sdcc2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x71 },
	{ .name = "gcc_sdcc3_apps_clk", .clk_mux = &gcc.mux, .mux = 0x78 },
	{ .name = "gcc_sdcc3_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x79 },
	{ .name = "gcc_sdcc4_apps_clk", .clk_mux = &gcc.mux, .mux = 0x80 },
	{ .name = "gcc_sdcc4_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x81 },
	{ .name = "gcc_blsp1_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x88 },
	{ .name = "gcc_blsp1_qup1_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x8a },
	{ .name = "gcc_blsp1_qup1_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x8b },
	{ .name = "gcc_blsp1_uart1_apps_clk", .clk_mux = &gcc.mux, .mux = 0x8c },
	{ .name = "gcc_blsp1_qup2_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x8e },
	{ .name = "gcc_blsp1_qup2_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x90 },
	{ .name = "gcc_blsp1_uart2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x91 },
	{ .name = "gcc_blsp1_qup3_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x93 },
	{ .name = "gcc_blsp1_qup3_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x94 },
	{ .name = "gcc_blsp1_uart3_apps_clk", .clk_mux = &gcc.mux, .mux = 0x95 },
	{ .name = "gcc_blsp1_qup4_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x98 },
	{ .name = "gcc_blsp1_qup4_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x99 },
	{ .name = "gcc_blsp1_uart4_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9a },
	{ .name = "gcc_blsp1_qup5_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9c },
	{ .name = "gcc_blsp1_qup5_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9d },
	{ .name = "gcc_blsp1_uart5_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9e },
	{ .name = "gcc_blsp1_qup6_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xa1 },
	{ .name = "gcc_blsp1_qup6_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xa2 },
	{ .name = "gcc_blsp1_uart6_apps_clk", .clk_mux = &gcc.mux, .mux = 0xa3 },
	{ .name = "gcc_blsp2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xa8 },
	{ .name = "gcc_blsp2_qup1_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xaa },
	{ .name = "gcc_blsp2_qup1_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xab },
	{ .name = "gcc_blsp2_uart1_apps_clk", .clk_mux = &gcc.mux, .mux = 0xac },
	{ .name = "gcc_blsp2_qup2_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xae },
	{ .name = "gcc_blsp2_qup2_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb0 },
	{ .name = "gcc_blsp2_uart2_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb1 },
	{ .name = "gcc_blsp2_qup3_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb3 },
	{ .name = "gcc_blsp2_qup3_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb4 },
	{ .name = "gcc_blsp2_uart3_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb5 },
	{ .name = "gcc_blsp2_qup4_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb8 },
	{ .name = "gcc_blsp2_qup4_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xb9 },
	{ .name = "gcc_blsp2_uart4_apps_clk", .clk_mux = &gcc.mux, .mux = 0xba },
	{ .name = "gcc_blsp2_qup5_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xbc },
	{ .name = "gcc_blsp2_qup5_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xbd },
	{ .name = "gcc_blsp2_uart5_apps_clk", .clk_mux = &gcc.mux, .mux = 0xbe },
	{ .name = "gcc_blsp2_qup6_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0xc1 },
	{ .name = "gcc_blsp2_qup6_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0xc2 },
	{ .name = "gcc_blsp2_uart6_apps_clk", .clk_mux = &gcc.mux, .mux = 0xc3 },
	{ .name = "gcc_pdm_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xd0 },
	{ .name = "gcc_pdm2_clk", .clk_mux = &gcc.mux, .mux = 0xd2 },
	{ .name = "gcc_prng_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xd8 },
	{ .name = "gcc_bam_dma_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xe0 },
	{ .name = "gcc_tsif_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xe8 },
	{ .name = "gcc_tsif_ref_clk", .clk_mux = &gcc.mux, .mux = 0xe9 },
	{ .name = "gcc_boot_rom_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xf8 },
	{ .name = "gcc_lpass_q6_axi_clk", .clk_mux = &gcc.mux, .mux = 0x160 },
	{ .name = "gcc_pcie_0_slv_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1e8 },
	{ .name = "gcc_pcie_0_mstr_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1e9 },
	{ .name = "gcc_pcie_0_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x1ea },
	{ .name = "gcc_pcie_0_aux_clk", .clk_mux = &gcc.mux, .mux = 0x1eb },
	{ .name = "gcc_pcie_0_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x1ec },
	{ .name = "gcc_pcie_1_slv_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1f0 },
	{ .name = "gcc_pcie_1_mstr_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1f1 },
	{ .name = "gcc_pcie_1_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x1f2 },
	{ .name = "gcc_pcie_1_aux_clk", .clk_mux = &gcc.mux, .mux = 0x1f3 },
	{ .name = "gcc_pcie_1_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x1f4 },
	{ .name = "gcc_ufs_axi_clk", .clk_mux = &gcc.mux, .mux = 0x230 },
	{ .name = "gcc_ufs_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x231 },
	{ .name = "gcc_ufs_tx_cfg_clk", .clk_mux = &gcc.mux, .mux = 0x232 },
	{ .name = "gcc_ufs_rx_cfg_clk", .clk_mux = &gcc.mux, .mux = 0x233 },
	{ .name = "gcc_ufs_tx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x234 },
	{ .name = "gcc_ufs_tx_symbol_1_clk", .clk_mux = &gcc.mux, .mux = 0x235 },
	{ .name = "gcc_ufs_rx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x236 },
	{ .name = "gcc_ufs_rx_symbol_1_clk", .clk_mux = &gcc.mux, .mux = 0x237 },

	{ .name = "mmsscc_mmssnoc_ahb", .clk_mux = &mmcc, .mux = 0x1 },
	{ .name = "oxili_gfx3d_clk", .clk_mux = &mmcc, .mux = 0xd },
	{ .name = "mmss_misc_ahb_clk", .clk_mux = &mmcc, .mux = 0x3 },
	{ .name = "mmss_mmssnoc_axi_clk", .clk_mux = &mmcc, .mux = 0x4 },
	{ .name = "mmss_s0_axi_clk", .clk_mux = &mmcc, .mux = 0x5 },
	{ .name = "ocmemcx_ocmemnoc_clk", .clk_mux = &mmcc, .mux = 0x9 },
	{ .name = "oxilicx_ahb_clk", .clk_mux = &mmcc, .mux = 0xc },
	{ .name = "venus0_vcodec0_clk", .clk_mux = &mmcc, .mux = 0xe },
	{ .name = "venus0_axi_clk", .clk_mux = &mmcc, .mux = 0xf },
	{ .name = "venus0_ocmemnoc_clk", .clk_mux = &mmcc, .mux = 0x10 },
	{ .name = "venus0_ahb_clk", .clk_mux = &mmcc, .mux = 0x11 },
	{ .name = "mdss_mdp_clk", .clk_mux = &mmcc, .mux = 0x14 },
	{ .name = "mdss_pclk0_clk", .clk_mux = &mmcc, .mux = 0x16 },
	{ .name = "mdss_pclk1_clk", .clk_mux = &mmcc, .mux = 0x17 },
	{ .name = "mdss_extpclk_clk", .clk_mux = &mmcc, .mux = 0x18 },
	{ .name = "venus0_core0_vcodec_clk", .clk_mux = &mmcc, .mux = 0x1a },
	{ .name = "venus0_core1_vcodec_clk", .clk_mux = &mmcc, .mux = 0x1b },
	{ .name = "mdss_vsync_clk", .clk_mux = &mmcc, .mux = 0x1c },
	{ .name = "mdss_hdmi_clk", .clk_mux = &mmcc, .mux = 0x1d },
	{ .name = "mdss_byte0_clk", .clk_mux = &mmcc, .mux = 0x1e },
	{ .name = "mdss_byte1_clk", .clk_mux = &mmcc, .mux = 0x1f },
	{ .name = "mdss_esc0_clk", .clk_mux = &mmcc, .mux = 0x20 },
	{ .name = "mdss_esc1_clk", .clk_mux = &mmcc, .mux = 0x21 },
	{ .name = "mdss_ahb_clk", .clk_mux = &mmcc, .mux = 0x22 },
	{ .name = "mdss_hdmi_ahb_clk", .clk_mux = &mmcc, .mux = 0x23 },
	{ .name = "mdss_axi_clk", .clk_mux = &mmcc, .mux = 0x24 },
	{ .name = "camss_top_ahb_clk", .clk_mux = &mmcc, .mux = 0x25 },
	{ .name = "camss_micro_ahb_clk", .clk_mux = &mmcc, .mux = 0x26 },
	{ .name = "camss_gp0_clk", .clk_mux = &mmcc, .mux = 0x27 },
	{ .name = "camss_gp1_clk", .clk_mux = &mmcc, .mux = 0x28 },
	{ .name = "camss_mclk0_clk", .clk_mux = &mmcc, .mux = 0x29 },
	{ .name = "camss_mclk1_clk", .clk_mux = &mmcc, .mux = 0x2a },
	{ .name = "camss_mclk2_clk", .clk_mux = &mmcc, .mux = 0x2b },
	{ .name = "camss_mclk3_clk", .clk_mux = &mmcc, .mux = 0x2c },
	{ .name = "camss_cci_cci_clk", .clk_mux = &mmcc, .mux = 0x2d },
	{ .name = "camss_cci_cci_ahb_clk", .clk_mux = &mmcc, .mux = 0x2e },
	{ .name = "camss_phy0_csi0phytimer_clk", .clk_mux = &mmcc, .mux = 0x2f },
	{ .name = "camss_phy1_csi1phytimer_clk", .clk_mux = &mmcc, .mux = 0x30 },
	{ .name = "camss_phy2_csi2phytimer_clk", .clk_mux = &mmcc, .mux = 0x31 },
	{ .name = "camss_jpeg_jpeg0_clk", .clk_mux = &mmcc, .mux = 0x32 },
	{ .name = "camss_jpeg_jpeg1_clk", .clk_mux = &mmcc, .mux = 0x33 },
	{ .name = "camss_jpeg_jpeg2_clk", .clk_mux = &mmcc, .mux = 0x34 },
	{ .name = "camss_jpeg_jpeg_ahb_clk", .clk_mux = &mmcc, .mux = 0x35 },
	{ .name = "camss_jpeg_jpeg_axi_clk", .clk_mux = &mmcc, .mux = 0x36 },
	{ .name = "camss_ahb_clk", .clk_mux = &mmcc, .mux = 0x37 },
	{ .name = "camss_vfe_vfe0_clk", .clk_mux = &mmcc, .mux = 0x38 },
	{ .name = "camss_vfe_vfe1_clk", .clk_mux = &mmcc, .mux = 0x39 },
	{ .name = "camss_vfe_cpp_clk", .clk_mux = &mmcc, .mux = 0x3a },
	{ .name = "camss_vfe_cpp_ahb_clk", .clk_mux = &mmcc, .mux = 0x3b },
	{ .name = "camss_vfe_vfe_ahb_clk", .clk_mux = &mmcc, .mux = 0x3c },
	{ .name = "camss_vfe_vfe_axi_clk", .clk_mux = &mmcc, .mux = 0x3d },
	{ .name = "oxili_rbbmtimer_clk", .clk_mux = &mmcc, .mux = 0x3e },
	{ .name = "camss_csi_vfe0_clk", .clk_mux = &mmcc, .mux = 0x3f },
	{ .name = "camss_csi_vfe1_clk", .clk_mux = &mmcc, .mux = 0x40 },
	{ .name = "camss_csi0_clk", .clk_mux = &mmcc, .mux = 0x41 },
	{ .name = "camss_csi0_ahb_clk", .clk_mux = &mmcc, .mux = 0x42 },
	{ .name = "camss_csi0phy_clk", .clk_mux = &mmcc, .mux = 0x43 },
	{ .name = "camss_csi0rdi_clk", .clk_mux = &mmcc, .mux = 0x44 },
	{ .name = "camss_csi0pix_clk", .clk_mux = &mmcc, .mux = 0x45 },
	{ .name = "camss_csi1_clk", .clk_mux = &mmcc, .mux = 0x46 },
	{ .name = "camss_csi1_ahb_clk", .clk_mux = &mmcc, .mux = 0x47 },
	{ .name = "camss_csi1phy_clk", .clk_mux = &mmcc, .mux = 0x48 },
	{ .name = "camss_csi1rdi_clk", .clk_mux = &mmcc, .mux = 0x49 },
	{ .name = "camss_csi1pix_clk", .clk_mux = &mmcc, .mux = 0x4a },
	{ .name = "camss_csi2_clk", .clk_mux = &mmcc, .mux = 0x4b },
	{ .name = "camss_csi2_ahb_clk", .clk_mux = &mmcc, .mux = 0x4c },
	{ .name = "camss_csi2phy_clk", .clk_mux = &mmcc, .mux = 0x4d },
	{ .name = "camss_csi2rdi_clk", .clk_mux = &mmcc, .mux = 0x4e },
	{ .name = "camss_csi2pix_clk", .clk_mux = &mmcc, .mux = 0x4f },
	{ .name = "camss_csi3_clk", .clk_mux = &mmcc, .mux = 0x50 },
	{ .name = "camss_csi3_ahb_clk", .clk_mux = &mmcc, .mux = 0x51 },
	{ .name = "camss_csi3phy_clk", .clk_mux = &mmcc, .mux = 0x52 },
	{ .name = "camss_csi3rdi_clk", .clk_mux = &mmcc, .mux = 0x53 },
	{ .name = "camss_csi3pix_clk", .clk_mux = &mmcc, .mux = 0x54 },
	{ .name = "camss_ispif_ahb_clk", .clk_mux = &mmcc, .mux = 0x55 },
	{ .name = "venus0_core2_vcodec_clk", .clk_mux = &mmcc, .mux = 0x79 },
	{ .name = "camss_vfe_cpp_axi_clk", .clk_mux = &mmcc, .mux = 0x7a },
	{ .name = "camss_jpeg_dma_clk", .clk_mux = &mmcc, .mux = 0x7b },
	{ .name = "fd_core_clk", .clk_mux = &mmcc, .mux = 0x89 },
	{ .name = "fd_core_uar_clk", .clk_mux = &mmcc, .mux = 0x8a },
	{ .name = "fd_axi_clk", .clk_mux = &mmcc, .mux = 0x8b },
	{ .name = "fd_ahb_clk", .clk_mux = &mmcc, .mux = 0x8c },
	{}
};

struct debugcc_platform msm8994_debugcc = {
	.name = "msm8994",
	.clocks = msm8994_clocks,
};
