// SPDX-License-Identifier: BSD-3-Clause
/* Copyright (c) 2022, Linaro Limited */

#include <sys/mman.h>
#include <err.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "debugcc.h"

static struct gcc_mux gcc = {
	.mux = {
		.phys = 0x100000,
		.size = 0xb0000,

		.measure = measure_gcc,

		.enable_reg = 0x62000,
		.enable_mask = BIT(16),

		.mux_reg = 0x62000,
		.mux_mask = 0x3ff,

		.div_reg = 0x62000,
		.div_mask = 0xf,
		.div_val = 4,
	},

	.xo_div4_reg = 0x43008,
	.debug_ctl_reg = 0x62004,
	.debug_status_reg = 0x62008,
};

static struct debug_mux mm_cc = {
	.phys = 0xc8c0000,
	.size = 0x40000,
	.block_name = "mm",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x22,

	.enable_reg = 0x900,
	.enable_mask = BIT(16),

	.mux_reg = 0x900,
	.mux_mask = 0x3ff,
};

static struct debug_mux gpu_cc = {
	.phys = 0x5065000,
	.size = 0x9000,
	.block_name = "gpu",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x13d,

	.enable_reg = 0x120,
	.enable_mask = BIT(16),

	.mux_reg = 0x120,
	.mux_mask = 0x3ff,
};

static struct measure_clk msm8998_clocks[] = {
	// { "debug_cpu_clk", &gcc.mux, 0xc0 },

	{ .name = "snoc_clk", .clk_mux = &gcc.mux, .mux = 0x0 },
	{ .name = "cnoc_clk", .clk_mux = &gcc.mux, .mux = 0xe },
	{ .name = "bimc_clk", .clk_mux = &gcc.mux, .mux = 0x14e },
	{ .name = "gcc_mmss_sys_noc_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1f },
	{ .name = "gcc_mmss_noc_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x20 },
	{ .name = "gcc_usb30_master_clk", .clk_mux = &gcc.mux, .mux = 0x3e },
	{ .name = "gcc_usb30_sleep_clk", .clk_mux = &gcc.mux, .mux = 0x3f },
	{ .name = "gcc_usb30_mock_utmi_clk", .clk_mux = &gcc.mux, .mux = 0x40 },
	{ .name = "gcc_usb3_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x41 },
	{ .name = "gcc_usb3_phy_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x42 },
	{ .name = "gcc_sdcc2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x46 },
	{ .name = "gcc_sdcc2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x47 },
	{ .name = "gcc_sdcc4_apps_clk", .clk_mux = &gcc.mux, .mux = 0x48 },
	{ .name = "gcc_sdcc4_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x49 },
	{ .name = "gcc_blsp1_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x4a },
	{ .name = "gcc_blsp1_qup1_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x4c },
	{ .name = "gcc_blsp1_qup1_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x4d },
	{ .name = "gcc_blsp1_uart1_apps_clk", .clk_mux = &gcc.mux, .mux = 0x4e },
	{ .name = "gcc_blsp1_qup2_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x50 },
	{ .name = "gcc_blsp1_qup2_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x51 },
	{ .name = "gcc_blsp1_uart2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x52 },
	{ .name = "gcc_blsp1_qup3_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x54 },
	{ .name = "gcc_blsp1_qup3_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x55 },
	{ .name = "gcc_blsp1_uart3_apps_clk", .clk_mux = &gcc.mux, .mux = 0x56 },
	{ .name = "gcc_blsp1_qup4_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x58 },
	{ .name = "gcc_blsp1_qup4_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x59 },
	{ .name = "gcc_blsp1_qup5_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x5a },
	{ .name = "gcc_blsp1_qup5_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x5b },
	{ .name = "gcc_blsp1_qup6_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x5c },
	{ .name = "gcc_blsp1_qup6_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x5d },
	{ .name = "gcc_blsp2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x5e },
	{ .name = "gcc_blsp2_qup1_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x60 },
	{ .name = "gcc_blsp2_qup1_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x61 },
	{ .name = "gcc_blsp2_uart1_apps_clk", .clk_mux = &gcc.mux, .mux = 0x62 },
	{ .name = "gcc_blsp2_qup2_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x64 },
	{ .name = "gcc_blsp2_qup2_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x65 },
	{ .name = "gcc_blsp2_uart2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x66 },
	{ .name = "gcc_blsp2_qup3_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x68 },
	{ .name = "gcc_blsp2_qup3_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x69 },
	{ .name = "gcc_blsp2_uart3_apps_clk", .clk_mux = &gcc.mux, .mux = 0x6a },
	{ .name = "gcc_blsp2_qup4_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x6c },
	{ .name = "gcc_blsp2_qup4_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x6d },
	{ .name = "gcc_blsp2_qup5_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x6e },
	{ .name = "gcc_blsp2_qup5_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x6f },
	{ .name = "gcc_blsp2_qup6_spi_apps_clk", .clk_mux = &gcc.mux, .mux = 0x70 },
	{ .name = "gcc_blsp2_qup6_i2c_apps_clk", .clk_mux = &gcc.mux, .mux = 0x71 },
	{ .name = "gcc_pdm_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x72 },
	{ .name = "gcc_pdm2_clk", .clk_mux = &gcc.mux, .mux = 0x74},
	{ .name = "gcc_prng_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x75 },
	{ .name = "gcc_tsif_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x76 },
	{ .name = "gcc_tsif_ref_clk", .clk_mux = &gcc.mux, .mux = 0x77 },
	{ .name = "gcc_boot_rom_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x7a },
	{ .name = "ce1_clk", .clk_mux = &gcc.mux, .mux = 0x97 },
	{ .name = "gcc_ce1_axi_m_clk", .clk_mux = &gcc.mux, .mux = 0x98 },
	{ .name = "gcc_ce1_ahb_m_clk", .clk_mux = &gcc.mux, .mux = 0x99 },
	{ .name = "measure_only_bimc_hmss_axi_clk", .clk_mux = &gcc.mux, .mux = 0xbb },
	{ .name = "gcc_bimc_gfx_clk", .clk_mux = &gcc.mux, .mux = 0xac },
	{ .name = "gcc_hmss_rbcpr_clk", .clk_mux = &gcc.mux, .mux = 0xbc },
	{ .name = "gcc_gp1_clk", .clk_mux = &gcc.mux, .mux = 0xdf },
	{ .name = "gcc_gp2_clk", .clk_mux = &gcc.mux, .mux = 0xe0 },
	{ .name = "gcc_gp3_clk", .clk_mux = &gcc.mux, .mux = 0xe1 },
	{ .name = "gcc_pcie_0_slv_axi_clk", .clk_mux = &gcc.mux, .mux = 0xe2 },
	{ .name = "gcc_pcie_0_mstr_axi_clk", .clk_mux = &gcc.mux, .mux = 0xe3 },
	{ .name = "gcc_pcie_0_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xe4 },
	{ .name = "gcc_pcie_0_aux_clk", .clk_mux = &gcc.mux, .mux = 0xe5 },
	{ .name = "gcc_pcie_0_pipe_clk", .clk_mux = &gcc.mux, .mux = 0xe6 },
	{ .name = "gcc_pcie_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0xe8 },
	{ .name = "gcc_ufs_axi_clk", .clk_mux = &gcc.mux, .mux = 0xea },
	{ .name = "gcc_ufs_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xeb },
	{ .name = "gcc_ufs_tx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0xec },
	{ .name = "gcc_ufs_rx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0xed },
	{ .name = "gcc_ufs_rx_symbol_1_clk", .clk_mux = &gcc.mux, .mux = 0x162 },
	{ .name = "gcc_ufs_unipro_core_clk", .clk_mux = &gcc.mux, .mux = 0xf0 },
	{ .name = "gcc_ufs_ice_core_clk", .clk_mux = &gcc.mux, .mux = 0xf1 },
	{ .name = "gcc_dcc_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x119 },
	{ .name = "ipa_clk", .clk_mux = &gcc.mux, .mux = 0x11b },
	{ .name = "gcc_mss_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x11f },
	{ .name = "gcc_mss_q6_bimc_axi_clk", .clk_mux = &gcc.mux, .mux = 0x124 },
	{ .name = "gcc_mss_mnoc_bimc_axi_clk", .clk_mux = &gcc.mux, .mux = 0x120 },
	{ .name = "gcc_mss_snoc_axi_clk", .clk_mux = &gcc.mux, .mux = 0x123 },
	{ .name = "gcc_gpu_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x13b },
	{ .name = "gcc_gpu_bimc_gfx_clk", .clk_mux = &gcc.mux, .mux = 0x13f },
	{ .name = "gcc_qspi_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x156 },
	{ .name = "gcc_qspi_ref_clk", .clk_mux = &gcc.mux, .mux = 0x157 },

	{ .name = "mmss_mnoc_ahb_clk", .clk_mux = &mm_cc, .mux = 0x1 },
	{ .name = "mmss_misc_ahb_clk", .clk_mux = &mm_cc, .mux = 0x3 },
	{ .name = "mmss_vmem_maxi_clk", .clk_mux = &mm_cc, .mux = 0x9 },
	{ .name = "mmss_vmem_ahb_clk", .clk_mux = &mm_cc, .mux = 0xa },
	{ .name = "mmss_bimc_smmu_ahb_clk", .clk_mux = &mm_cc, .mux = 0xc },
	{ .name = "mmss_bimc_smmu_axi_clk", .clk_mux = &mm_cc, .mux = 0xd },
	{ .name = "mmss_video_core_clk", .clk_mux = &mm_cc, .mux = 0xe },
	{ .name = "mmss_video_axi_clk", .clk_mux = &mm_cc, .mux = 0xf },
	{ .name = "mmss_video_maxi_clk", .clk_mux = &mm_cc, .mux = 0x10 },
	{ .name = "mmss_video_ahb_clk", .clk_mux = &mm_cc, .mux = 0x11 },
	{ .name = "mmss_mdss_rot_clk", .clk_mux = &mm_cc, .mux = 0x12 },
	{ .name = "mmss_snoc_dvm_axi_clk", .clk_mux = &mm_cc, .mux = 0x13 },
	{ .name = "mmss_mdss_mdp_clk", .clk_mux = &mm_cc, .mux = 0x14 },
	{ .name = "mmss_mdss_mdp_lut_clk", .clk_mux = &mm_cc, .mux = 0x15 },
	{ .name = "mmss_mdss_pclk0_clk", .clk_mux = &mm_cc, .mux = 0x16 },
	{ .name = "mmss_mdss_pclk1_clk", .clk_mux = &mm_cc, .mux = 0x17 },
	{ .name = "mmss_mdss_extpclk_clk", .clk_mux = &mm_cc, .mux = 0x18 },
	{ .name = "mmss_video_subcore0_clk", .clk_mux = &mm_cc, .mux = 0x1a },
	{ .name = "mmss_video_subcore1_clk", .clk_mux = &mm_cc, .mux = 0x1b },
	{ .name = "mmss_mdss_vsync_clk", .clk_mux = &mm_cc, .mux = 0x1c },
	{ .name = "mmss_mdss_hdmi_clk", .clk_mux = &mm_cc, .mux = 0x1d },
	{ .name = "mmss_mdss_byte0_clk", .clk_mux = &mm_cc, .mux = 0x1e },
	{ .name = "mmss_mdss_byte1_clk", .clk_mux = &mm_cc, .mux = 0x1f },
	{ .name = "mmss_mdss_esc0_clk", .clk_mux = &mm_cc, .mux = 0x20 },
	{ .name = "mmss_mdss_esc1_clk", .clk_mux = &mm_cc, .mux = 0x21 },
	{ .name = "mmss_mdss_ahb_clk", .clk_mux = &mm_cc, .mux = 0x22 },
	{ .name = "mmss_mdss_hdmi_dp_ahb_clk", .clk_mux = &mm_cc, .mux = 0x23 },
	{ .name = "mmss_mdss_axi_clk", .clk_mux = &mm_cc, .mux = 0x24 },
	{ .name = "mmss_camss_top_ahb_clk", .clk_mux = &mm_cc, .mux = 0x25 },
	{ .name = "mmss_camss_micro_ahb_clk", .clk_mux = &mm_cc, .mux = 0x26 },
	{ .name = "mmss_camss_gp0_clk", .clk_mux = &mm_cc, .mux = 0x27 },
	{ .name = "mmss_camss_gp1_clk", .clk_mux = &mm_cc, .mux = 0x28 },
	{ .name = "mmss_camss_mclk0_clk", .clk_mux = &mm_cc, .mux = 0x29 },
	{ .name = "mmss_camss_mclk1_clk", .clk_mux = &mm_cc, .mux = 0x2a },
	{ .name = "mmss_camss_mclk2_clk", .clk_mux = &mm_cc, .mux = 0x2b },
	{ .name = "mmss_camss_mclk3_clk", .clk_mux = &mm_cc, .mux = 0x2c },
	{ .name = "mmss_camss_cci_clk", .clk_mux = &mm_cc, .mux = 0x2d },
	{ .name = "mmss_camss_cci_ahb_clk", .clk_mux = &mm_cc, .mux = 0x2e },
	{ .name = "mmss_camss_csi0phytimer_clk", .clk_mux = &mm_cc, .mux = 0x2f },
	{ .name = "mmss_camss_csi1phytimer_clk", .clk_mux = &mm_cc, .mux = 0x30 },
	{ .name = "mmss_camss_csi2phytimer_clk", .clk_mux = &mm_cc, .mux = 0x31 },
	{ .name = "mmss_camss_jpeg0_clk", .clk_mux = &mm_cc, .mux = 0x32 },
	{ .name = "mmss_camss_ispif_ahb_clk", .clk_mux = &mm_cc, .mux = 0x33 },
	{ .name = "mmss_camss_jpeg_ahb_clk", .clk_mux = &mm_cc, .mux = 0x35 },
	{ .name = "mmss_camss_jpeg_axi_clk", .clk_mux = &mm_cc, .mux = 0x36 },
	{ .name = "mmss_camss_ahb_clk", .clk_mux = &mm_cc, .mux = 0x37 },
	{ .name = "mmss_camss_vfe0_clk", .clk_mux = &mm_cc, .mux = 0x38 },
	{ .name = "mmss_camss_vfe1_clk", .clk_mux = &mm_cc, .mux = 0x39 },
	{ .name = "mmss_camss_cpp_clk", .clk_mux = &mm_cc, .mux = 0x3a },
	{ .name = "mmss_camss_cpp_ahb_clk", .clk_mux = &mm_cc, .mux = 0x3b },
	{ .name = "mmss_camss_csi_vfe0_clk", .clk_mux = &mm_cc, .mux = 0x3f },
	{ .name = "mmss_camss_csi_vfe1_clk", .clk_mux = &mm_cc, .mux = 0x40 },
	{ .name = "mmss_camss_csi0_clk", .clk_mux = &mm_cc, .mux = 0x41 },
	{ .name = "mmss_camss_csi0_ahb_clk", .clk_mux = &mm_cc, .mux = 0x42 },
	{ .name = "mmss_camss_csiphy0_clk", .clk_mux = &mm_cc, .mux = 0x43 },
	{ .name = "mmss_camss_csi0rdi_clk", .clk_mux = &mm_cc, .mux = 0x44 },
	{ .name = "mmss_camss_csi0pix_clk", .clk_mux = &mm_cc, .mux = 0x45 },
	{ .name = "mmss_camss_csi1_clk", .clk_mux = &mm_cc, .mux = 0x46 },
	{ .name = "mmss_camss_csi1_ahb_clk", .clk_mux = &mm_cc, .mux = 0x47 },
	{ .name = "mmss_camss_csi1rdi_clk", .clk_mux = &mm_cc, .mux = 0x49 },
	{ .name = "mmss_camss_csi1pix_clk", .clk_mux = &mm_cc, .mux = 0x4a },
	{ .name = "mmss_camss_csi2_clk", .clk_mux = &mm_cc, .mux = 0x4b },
	{ .name = "mmss_camss_csi2_ahb_clk", .clk_mux = &mm_cc, .mux = 0x4c },
	{ .name = "mmss_camss_csi2rdi_clk", .clk_mux = &mm_cc, .mux = 0x4e },
	{ .name = "mmss_camss_csi2pix_clk", .clk_mux = &mm_cc, .mux = 0x4f },
	{ .name = "mmss_camss_csi3_clk", .clk_mux = &mm_cc, .mux = 0x50 },
	{ .name = "mmss_camss_csi3_ahb_clk", .clk_mux = &mm_cc, .mux = 0x51 },
	{ .name = "mmss_camss_csi3rdi_clk", .clk_mux = &mm_cc, .mux = 0x53 },
	{ .name = "mmss_camss_csi3pix_clk", .clk_mux = &mm_cc, .mux = 0x54 },
	{ .name = "mmss_mnoc_maxi_clk", .clk_mux = &mm_cc, .mux = 0x70 },
	{ .name = "mmss_camss_vfe0_stream_clk", .clk_mux = &mm_cc, .mux = 0x71 },
	{ .name = "mmss_camss_vfe1_stream_clk", .clk_mux = &mm_cc, .mux = 0x72 },
	{ .name = "mmss_camss_cpp_vbif_ahb_clk", .clk_mux = &mm_cc, .mux = 0x73 },
	{ .name = "mmss_misc_cxo_clk", .clk_mux = &mm_cc, .mux = 0x77 },
	{ .name = "mmss_camss_cpp_axi_clk", .clk_mux = &mm_cc, .mux = 0x7a },
	{ .name = "mmss_camss_csiphy1_clk", .clk_mux = &mm_cc, .mux = 0x85 },
	{ .name = "mmss_camss_vfe0_ahb_clk", .clk_mux = &mm_cc, .mux = 0x86 },
	{ .name = "mmss_camss_vfe1_ahb_clk", .clk_mux = &mm_cc, .mux = 0x87 },
	{ .name = "mmss_camss_csiphy2_clk", .clk_mux = &mm_cc, .mux = 0x88 },
	{ .name = "mmss_fd_core_clk", .clk_mux = &mm_cc, .mux = 0x89 },
	{ .name = "mmss_fd_core_uar_clk", .clk_mux = &mm_cc, .mux = 0x8a },
	{ .name = "mmss_fd_ahb_clk", .clk_mux = &mm_cc, .mux = 0x8c },
	{ .name = "mmss_camss_cphy_csid0_clk", .clk_mux = &mm_cc, .mux = 0x8d },
	{ .name = "mmss_camss_cphy_csid1_clk", .clk_mux = &mm_cc, .mux = 0x8e },
	{ .name = "mmss_camss_cphy_csid2_clk", .clk_mux = &mm_cc, .mux = 0x8f },
	{ .name = "mmss_camss_cphy_csid3_clk", .clk_mux = &mm_cc, .mux = 0x90 },
	{ .name = "mmss_mdss_dp_link_clk", .clk_mux = &mm_cc, .mux = 0x98 },
	{ .name = "mmss_mdss_dp_link_intf_clk", .clk_mux = &mm_cc, .mux = 0x99 },
	{ .name = "mmss_mdss_dp_crypto_clk", .clk_mux = &mm_cc, .mux = 0x9a },
	{ .name = "mmss_mdss_dp_pixel_clk", .clk_mux = &mm_cc, .mux = 0x9b },
	{ .name = "mmss_mdss_dp_aux_clk", .clk_mux = &mm_cc, .mux = 0x9c },
	{ .name = "mmss_mdss_dp_gtc_clk", .clk_mux = &mm_cc, .mux = 0x9d },
	{ .name = "mmss_mdss_byte0_intf_clk", .clk_mux = &mm_cc, .mux = 0xad },
	{ .name = "mmss_mdss_byte1_intf_clk", .clk_mux = &mm_cc, .mux = 0xae },

	{ .name = "gpucc_rbcpr_clk", .clk_mux = &gpu_cc, .mux = 0x3 },
	{ .name = "gpucc_rbbmtimer_clk", .clk_mux = &gpu_cc, .mux = 0x5 },
	{ .name = "gpucc_gfx3d_isense_clk", .clk_mux = &gpu_cc, .mux = 0xa },
	{}
};

struct debugcc_platform msm8998_debugcc = {
	.name = "msm8998",
	.clocks = msm8998_clocks,
};
