/*
 * Copyright (c) 2023, Linaro Ltd.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <sys/mman.h>
#include <err.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "debugcc.h"

static struct gcc_mux gcc = {
	.mux = {
		.phys =	0x100000,
		.size = 0x1f4200,

		.measure = measure_gcc,

		.enable_reg = 0x62004,
		.enable_mask = BIT(0),

		.mux_reg = 0x62024,
		.mux_mask = 0x3ff,

		.div_reg = 0x62000,
		.div_mask = 0xf,
		.div_val = 2,
	},

	.xo_div4_reg = 0x62008,
	.debug_ctl_reg = 0x62048,
	.debug_status_reg = 0x6204c,
};

static struct debug_mux cam_cc = {
	.phys = 0xade0000,
	.size = 0x20000,
	.block_name = "cam",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x6a,

	.enable_reg = 0x14008,
	.enable_mask = BIT(0),

	.mux_reg = 0x16000,
	.mux_mask = 0xff,

	.div_reg = 0x14004,
	.div_mask = 0xf,
	.div_val = 4,
};

static struct debug_mux disp_cc = {
	.phys = 0xaf00000,
	.size = 0x20000,
	.block_name = "disp",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x6f,

	.enable_reg = 0xd004,
	.enable_mask = BIT(0),

	.mux_reg = 0x11000,
	.mux_mask = 0x1ff,

	.div_reg = 0xd000,
	.div_mask = 0xf,
	.div_val = 4,
};

static struct debug_mux gpu_cc = {
	.phys = 0x3d90000,
	.size = 0xa000,
	.block_name = "gpu",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x18d,

	.enable_reg = 0x9274,
	.enable_mask = BIT(0),

	.mux_reg = 0x9564,
	.mux_mask = 0xff,

	.div_reg = 0x9270,
	.div_mask = 0xf,
	.div_val = 2,
};

static struct debug_mux video_cc = {
	.phys = 0xaaf0000,
	.size = 0x10000,
	.block_name = "video",

	.measure = measure_leaf,
	.parent = &gcc.mux,
	.parent_mux_val = 0x78,

	.enable_reg = 0x80fc,
	.enable_mask = BIT(0),

	.mux_reg = 0x9a4c,
	.mux_mask = 0x3f,

	.div_reg = 0x80f8,
	.div_mask = 0xf,
	.div_val = 3,
};

static struct measure_clk sm8650_clocks[] = {
	/* GCC entries */
	{ .name = "gcc_aggre_noc_pcie_axi_clk", .clk_mux = &gcc.mux, .mux = 0x3f },
	{ .name = "gcc_aggre_ufs_phy_axi_clk", .clk_mux = &gcc.mux, .mux = 0x41 },
	{ .name = "gcc_aggre_usb3_prim_axi_clk", .clk_mux = &gcc.mux, .mux = 0x40 },
	{ .name = "gcc_boot_rom_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xe2 },
	{ .name = "gcc_camera_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x62 },
	{ .name = "gcc_camera_hf_axi_clk", .clk_mux = &gcc.mux, .mux = 0x65 },
	{ .name = "gcc_camera_sf_axi_clk", .clk_mux = &gcc.mux, .mux = 0x67 },
	{ .name = "gcc_camera_xo_clk", .clk_mux = &gcc.mux, .mux = 0x69 },
	{ .name = "gcc_cfg_noc_pcie_anoc_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x2c },
	{ .name = "gcc_cfg_noc_usb3_prim_axi_clk", .clk_mux = &gcc.mux, .mux = 0x1e },
	{ .name = "gcc_cnoc_pcie_sf_axi_clk", .clk_mux = &gcc.mux, .mux = 0x18 },
	{ .name = "gcc_cpuss_ubwcp_clk", .clk_mux = &gcc.mux, .mux = 0x132 },
	{ .name = "gcc_ddrss_gpu_axi_clk", .clk_mux = &gcc.mux, .mux = 0xfe },
	{ .name = "gcc_ddrss_pcie_sf_qtb_clk", .clk_mux = &gcc.mux, .mux = 0xff },
	{ .name = "gcc_ddrss_ubwcp_clk", .clk_mux = &gcc.mux, .mux = 0x107 },
	{ .name = "gcc_disp_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x6b },
	{ .name = "gcc_disp_hf_axi_clk", .clk_mux = &gcc.mux, .mux = 0x6d },
	{ .name = "gcc_disp_xo_clk", .clk_mux = &gcc.mux, .mux = 0x6e },
	{ .name = "gcc_gp1_clk", .clk_mux = &gcc.mux, .mux = 0x144 },
	{ .name = "gcc_gp2_clk", .clk_mux = &gcc.mux, .mux = 0x145 },
	{ .name = "gcc_gp3_clk", .clk_mux = &gcc.mux, .mux = 0x146 },
	{ .name = "gcc_gpu_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x18a },
	{ .name = "gcc_gpu_gpll0_clk_src", .clk_mux = &gcc.mux, .mux = 0x191 },
	{ .name = "gcc_gpu_gpll0_div_clk_src", .clk_mux = &gcc.mux, .mux = 0x192 },
	{ .name = "gcc_gpu_memnoc_gfx_clk", .clk_mux = &gcc.mux, .mux = 0x18e },
	{ .name = "gcc_gpu_snoc_dvm_gfx_clk", .clk_mux = &gcc.mux, .mux = 0x190 },
	{ .name = "gcc_pcie_0_aux_clk", .clk_mux = &gcc.mux, .mux = 0x14c },
	{ .name = "gcc_pcie_0_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x14b },
	{ .name = "gcc_pcie_0_mstr_axi_clk", .clk_mux = &gcc.mux, .mux = 0x14a },
	{ .name = "gcc_pcie_0_phy_rchng_clk", .clk_mux = &gcc.mux, .mux = 0x14e },
	{ .name = "gcc_pcie_0_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x14d },
	{ .name = "gcc_pcie_0_slv_axi_clk", .clk_mux = &gcc.mux, .mux = 0x149 },
	{ .name = "gcc_pcie_0_slv_q2a_axi_clk", .clk_mux = &gcc.mux, .mux = 0x148 },
	{ .name = "gcc_pcie_1_aux_clk", .clk_mux = &gcc.mux, .mux = 0x155 },
	{ .name = "gcc_pcie_1_cfg_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x154 },
	{ .name = "gcc_pcie_1_mstr_axi_clk", .clk_mux = &gcc.mux, .mux = 0x153 },
	{ .name = "gcc_pcie_1_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x156 },
	{ .name = "gcc_pcie_1_phy_rchng_clk", .clk_mux = &gcc.mux, .mux = 0x158 },
	{ .name = "gcc_pcie_1_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x157 },
	{ .name = "gcc_pcie_1_slv_axi_clk", .clk_mux = &gcc.mux, .mux = 0x152 },
	{ .name = "gcc_pcie_1_slv_q2a_axi_clk", .clk_mux = &gcc.mux, .mux = 0x151 },
	{ .name = "gcc_pdm2_clk", .clk_mux = &gcc.mux, .mux = 0xd3 },
	{ .name = "gcc_pdm_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xd1 },
	{ .name = "gcc_pdm_xo4_clk", .clk_mux = &gcc.mux, .mux = 0xd2 },
	{ .name = "gcc_qmip_camera_nrt_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x63 },
	{ .name = "gcc_qmip_camera_rt_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x64 },
	{ .name = "gcc_qmip_disp_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x6c },
	{ .name = "gcc_qmip_gpu_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x18b },
	{ .name = "gcc_qmip_pcie_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x147 },
	{ .name = "gcc_qmip_video_cv_cpu_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x74 },
	{ .name = "gcc_qmip_video_cvp_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x71 },
	{ .name = "gcc_qmip_video_v_cpu_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x73 },
	{ .name = "gcc_qmip_video_vcodec_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x72 },
	{ .name = "gcc_qupv3_i2c_core_clk", .clk_mux = &gcc.mux, .mux = 0xa3 },
	{ .name = "gcc_qupv3_i2c_s0_clk", .clk_mux = &gcc.mux, .mux = 0xa4 },
	{ .name = "gcc_qupv3_i2c_s1_clk", .clk_mux = &gcc.mux, .mux = 0xa5 },
	{ .name = "gcc_qupv3_i2c_s2_clk", .clk_mux = &gcc.mux, .mux = 0xa6 },
	{ .name = "gcc_qupv3_i2c_s3_clk", .clk_mux = &gcc.mux, .mux = 0xa7 },
	{ .name = "gcc_qupv3_i2c_s4_clk", .clk_mux = &gcc.mux, .mux = 0xa8 },
	{ .name = "gcc_qupv3_i2c_s5_clk", .clk_mux = &gcc.mux, .mux = 0xa9 },
	{ .name = "gcc_qupv3_i2c_s6_clk", .clk_mux = &gcc.mux, .mux = 0xaa },
	{ .name = "gcc_qupv3_i2c_s7_clk", .clk_mux = &gcc.mux, .mux = 0xab },
	{ .name = "gcc_qupv3_i2c_s8_clk", .clk_mux = &gcc.mux, .mux = 0xac },
	{ .name = "gcc_qupv3_i2c_s9_clk", .clk_mux = &gcc.mux, .mux = 0xad },
	{ .name = "gcc_qupv3_i2c_s_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xa2 },
	{ .name = "gcc_qupv3_wrap1_core_2x_clk", .clk_mux = &gcc.mux, .mux = 0xb1 },
	{ .name = "gcc_qupv3_wrap1_core_clk", .clk_mux = &gcc.mux, .mux = 0xb0 },
	{ .name = "gcc_qupv3_wrap1_qspi_ref_clk", .clk_mux = &gcc.mux, .mux = 0xba },
	{ .name = "gcc_qupv3_wrap1_s0_clk", .clk_mux = &gcc.mux, .mux = 0xb2 },
	{ .name = "gcc_qupv3_wrap1_s1_clk", .clk_mux = &gcc.mux, .mux = 0xb3 },
	{ .name = "gcc_qupv3_wrap1_s2_clk", .clk_mux = &gcc.mux, .mux = 0xb4 },
	{ .name = "gcc_qupv3_wrap1_s3_clk", .clk_mux = &gcc.mux, .mux = 0xb5 },
	{ .name = "gcc_qupv3_wrap1_s4_clk", .clk_mux = &gcc.mux, .mux = 0xb6 },
	{ .name = "gcc_qupv3_wrap1_s5_clk", .clk_mux = &gcc.mux, .mux = 0xb7 },
	{ .name = "gcc_qupv3_wrap1_s6_clk", .clk_mux = &gcc.mux, .mux = 0xb8 },
	{ .name = "gcc_qupv3_wrap1_s7_clk", .clk_mux = &gcc.mux, .mux = 0xb9 },
	{ .name = "gcc_qupv3_wrap2_core_2x_clk", .clk_mux = &gcc.mux, .mux = 0xbe },
	{ .name = "gcc_qupv3_wrap2_core_clk", .clk_mux = &gcc.mux, .mux = 0xbd },
	{ .name = "gcc_qupv3_wrap2_ibi_ctrl_2_clk", .clk_mux = &gcc.mux, .mux = 0xc9 },
	{ .name = "gcc_qupv3_wrap2_ibi_ctrl_3_clk", .clk_mux = &gcc.mux, .mux = 0xca },
	{ .name = "gcc_qupv3_wrap2_s0_clk", .clk_mux = &gcc.mux, .mux = 0xbf },
	{ .name = "gcc_qupv3_wrap2_s1_clk", .clk_mux = &gcc.mux, .mux = 0xc0 },
	{ .name = "gcc_qupv3_wrap2_s2_clk", .clk_mux = &gcc.mux, .mux = 0xc1 },
	{ .name = "gcc_qupv3_wrap2_s3_clk", .clk_mux = &gcc.mux, .mux = 0xc2 },
	{ .name = "gcc_qupv3_wrap2_s4_clk", .clk_mux = &gcc.mux, .mux = 0xc3 },
	{ .name = "gcc_qupv3_wrap2_s5_clk", .clk_mux = &gcc.mux, .mux = 0xc4 },
	{ .name = "gcc_qupv3_wrap2_s6_clk", .clk_mux = &gcc.mux, .mux = 0xc5 },
	{ .name = "gcc_qupv3_wrap2_s7_clk", .clk_mux = &gcc.mux, .mux = 0xc6 },
	{ .name = "gcc_qupv3_wrap3_core_2x_clk", .clk_mux = &gcc.mux, .mux = 0xce },
	{ .name = "gcc_qupv3_wrap3_core_clk", .clk_mux = &gcc.mux, .mux = 0xcd },
	{ .name = "gcc_qupv3_wrap3_qspi_ref_clk", .clk_mux = &gcc.mux, .mux = 0xd0 },
	{ .name = "gcc_qupv3_wrap3_s0_clk", .clk_mux = &gcc.mux, .mux = 0xcf },
	{ .name = "gcc_qupv3_wrap_1_m_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xae },
	{ .name = "gcc_qupv3_wrap_1_s_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xaf },
	{ .name = "gcc_qupv3_wrap_2_ibi_2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xc7 },
	{ .name = "gcc_qupv3_wrap_2_ibi_3_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xc8 },
	{ .name = "gcc_qupv3_wrap_2_m_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xbb },
	{ .name = "gcc_qupv3_wrap_2_s_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xbc },
	{ .name = "gcc_qupv3_wrap_3_m_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xcb },
	{ .name = "gcc_qupv3_wrap_3_s_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xcc },
	{ .name = "gcc_sdcc2_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x9d },
	{ .name = "gcc_sdcc2_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9c },
	{ .name = "gcc_sdcc4_ahb_clk", .clk_mux = &gcc.mux, .mux = 0xa0 },
	{ .name = "gcc_sdcc4_apps_clk", .clk_mux = &gcc.mux, .mux = 0x9f },
	{ .name = "gcc_ufs_phy_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x15d },
	{ .name = "gcc_ufs_phy_axi_clk", .clk_mux = &gcc.mux, .mux = 0x15c },
	{ .name = "gcc_ufs_phy_ice_core_clk", .clk_mux = &gcc.mux, .mux = 0x163 },
	{ .name = "gcc_ufs_phy_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x164 },
	{ .name = "gcc_ufs_phy_rx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x15f },
	{ .name = "gcc_ufs_phy_rx_symbol_1_clk", .clk_mux = &gcc.mux, .mux = 0x165 },
	{ .name = "gcc_ufs_phy_tx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x15e },
	{ .name = "gcc_ufs_phy_unipro_core_clk", .clk_mux = &gcc.mux, .mux = 0x162 },
	{ .name = "gcc_usb30_prim_master_clk", .clk_mux = &gcc.mux, .mux = 0x8f },
	{ .name = "gcc_usb30_prim_mock_utmi_clk", .clk_mux = &gcc.mux, .mux = 0x91 },
	{ .name = "gcc_usb30_prim_sleep_clk", .clk_mux = &gcc.mux, .mux = 0x90 },
	{ .name = "gcc_usb3_prim_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x92 },
	{ .name = "gcc_usb3_prim_phy_com_aux_clk", .clk_mux = &gcc.mux, .mux = 0x93 },
	{ .name = "gcc_usb3_prim_phy_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x94 },
	{ .name = "gcc_video_ahb_clk", .clk_mux = &gcc.mux, .mux = 0x70 },
	{ .name = "gcc_video_axi0_clk", .clk_mux = &gcc.mux, .mux = 0x75 },
	{ .name = "gcc_video_axi1_clk", .clk_mux = &gcc.mux, .mux = 0x76 },
	{ .name = "gcc_video_xo_clk", .clk_mux = &gcc.mux, .mux = 0x77 },
	{ .name = "mc_cc_debug_mux", .clk_mux = &gcc.mux, .mux = 0x10b },
	{ .name = "measure_only_cnoc_clk", .clk_mux = &gcc.mux, .mux = 0x16 },
	{ .name = "measure_only_ipa_2x_clk", .clk_mux = &gcc.mux, .mux = 0x176 },
	{ .name = "measure_only_memnoc_clk", .clk_mux = &gcc.mux, .mux = 0x103 },
	{ .name = "measure_only_snoc_clk", .clk_mux = &gcc.mux, .mux = 0xb },
	{ .name = "pcie_0_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x14f },
	{ .name = "pcie_1_phy_aux_clk", .clk_mux = &gcc.mux, .mux = 0x15a },
	{ .name = "pcie_1_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x159 },
	{ .name = "ufs_phy_rx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x161 },
	{ .name = "ufs_phy_rx_symbol_1_clk", .clk_mux = &gcc.mux, .mux = 0x167 },
	{ .name = "ufs_phy_tx_symbol_0_clk", .clk_mux = &gcc.mux, .mux = 0x160 },
	{ .name = "usb3_phy_wrapper_gcc_usb30_pipe_clk", .clk_mux = &gcc.mux, .mux = 0x98 },
	/* CAMCC Entries */
	{ .name = "cam_cc_bps_ahb_clk", .clk_mux = &cam_cc, .mux = 0x17 },
	{ .name = "cam_cc_bps_clk", .clk_mux = &cam_cc, .mux = 0x18 },
	{ .name = "cam_cc_bps_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x16 },
	{ .name = "cam_cc_bps_shift_clk", .clk_mux = &cam_cc, .mux = 0x7b },
	{ .name = "cam_cc_camnoc_axi_nrt_clk", .clk_mux = &cam_cc, .mux = 0x86 },
	{ .name = "cam_cc_camnoc_axi_rt_clk", .clk_mux = &cam_cc, .mux = 0x49 },
	{ .name = "cam_cc_camnoc_dcd_xo_clk", .clk_mux = &cam_cc, .mux = 0x4a },
	{ .name = "cam_cc_camnoc_xo_clk", .clk_mux = &cam_cc, .mux = 0x60 },
	{ .name = "cam_cc_cci_0_clk", .clk_mux = &cam_cc, .mux = 0x44 },
	{ .name = "cam_cc_cci_1_clk", .clk_mux = &cam_cc, .mux = 0x45 },
	{ .name = "cam_cc_cci_2_clk", .clk_mux = &cam_cc, .mux = 0x61 },
	{ .name = "cam_cc_core_ahb_clk", .clk_mux = &cam_cc, .mux = 0x4d },
	{ .name = "cam_cc_cpas_ahb_clk", .clk_mux = &cam_cc, .mux = 0x46 },
	{ .name = "cam_cc_cpas_bps_clk", .clk_mux = &cam_cc, .mux = 0x19 },
	{ .name = "cam_cc_cpas_cre_clk", .clk_mux = &cam_cc, .mux = 0x5d },
	{ .name = "cam_cc_cpas_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x47 },
	{ .name = "cam_cc_cpas_ife_0_clk", .clk_mux = &cam_cc, .mux = 0x25 },
	{ .name = "cam_cc_cpas_ife_1_clk", .clk_mux = &cam_cc, .mux = 0x2a },
	{ .name = "cam_cc_cpas_ife_2_clk", .clk_mux = &cam_cc, .mux = 0x2f },
	{ .name = "cam_cc_cpas_ife_lite_clk", .clk_mux = &cam_cc, .mux = 0x34 },
	{ .name = "cam_cc_cpas_ipe_nps_clk", .clk_mux = &cam_cc, .mux = 0x1b },
	{ .name = "cam_cc_cpas_sbi_clk", .clk_mux = &cam_cc, .mux = 0x22 },
	{ .name = "cam_cc_cpas_sfe_0_clk", .clk_mux = &cam_cc, .mux = 0x39 },
	{ .name = "cam_cc_cpas_sfe_1_clk", .clk_mux = &cam_cc, .mux = 0x3d },
	{ .name = "cam_cc_cpas_sfe_2_clk", .clk_mux = &cam_cc, .mux = 0x78 },
	{ .name = "cam_cc_cre_ahb_clk", .clk_mux = &cam_cc, .mux = 0x5e },
	{ .name = "cam_cc_cre_clk", .clk_mux = &cam_cc, .mux = 0x5c },
	{ .name = "cam_cc_csi0phytimer_clk", .clk_mux = &cam_cc, .mux = 0x9 },
	{ .name = "cam_cc_csi1phytimer_clk", .clk_mux = &cam_cc, .mux = 0xc },
	{ .name = "cam_cc_csi2phytimer_clk", .clk_mux = &cam_cc, .mux = 0xe },
	{ .name = "cam_cc_csi3phytimer_clk", .clk_mux = &cam_cc, .mux = 0x10 },
	{ .name = "cam_cc_csi4phytimer_clk", .clk_mux = &cam_cc, .mux = 0x12 },
	{ .name = "cam_cc_csi5phytimer_clk", .clk_mux = &cam_cc, .mux = 0x14 },
	{ .name = "cam_cc_csi6phytimer_clk", .clk_mux = &cam_cc, .mux = 0x58 },
	{ .name = "cam_cc_csi7phytimer_clk", .clk_mux = &cam_cc, .mux = 0x5a },
	{ .name = "cam_cc_csid_clk", .clk_mux = &cam_cc, .mux = 0x48 },
	{ .name = "cam_cc_csid_csiphy_rx_clk", .clk_mux = &cam_cc, .mux = 0xb },
	{ .name = "cam_cc_csiphy0_clk", .clk_mux = &cam_cc, .mux = 0xa },
	{ .name = "cam_cc_csiphy1_clk", .clk_mux = &cam_cc, .mux = 0xd },
	{ .name = "cam_cc_csiphy2_clk", .clk_mux = &cam_cc, .mux = 0xf },
	{ .name = "cam_cc_csiphy3_clk", .clk_mux = &cam_cc, .mux = 0x11 },
	{ .name = "cam_cc_csiphy4_clk", .clk_mux = &cam_cc, .mux = 0x13 },
	{ .name = "cam_cc_csiphy5_clk", .clk_mux = &cam_cc, .mux = 0x15 },
	{ .name = "cam_cc_csiphy6_clk", .clk_mux = &cam_cc, .mux = 0x59 },
	{ .name = "cam_cc_csiphy7_clk", .clk_mux = &cam_cc, .mux = 0x5b },
	{ .name = "cam_cc_drv_ahb_clk", .clk_mux = &cam_cc, .mux = 0x75 },
	{ .name = "cam_cc_drv_xo_clk", .clk_mux = &cam_cc, .mux = 0x74 },
	{ .name = "cam_cc_gdsc_clk", .clk_mux = &cam_cc, .mux = 0x4e },
	{ .name = "cam_cc_icp_ahb_clk", .clk_mux = &cam_cc, .mux = 0x43 },
	{ .name = "cam_cc_icp_clk", .clk_mux = &cam_cc, .mux = 0x42 },
	{ .name = "cam_cc_ife_0_clk", .clk_mux = &cam_cc, .mux = 0x24 },
	{ .name = "cam_cc_ife_0_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x28 },
	{ .name = "cam_cc_ife_0_shift_clk", .clk_mux = &cam_cc, .mux = 0x7f },
	{ .name = "cam_cc_ife_1_clk", .clk_mux = &cam_cc, .mux = 0x29 },
	{ .name = "cam_cc_ife_1_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x2d },
	{ .name = "cam_cc_ife_1_shift_clk", .clk_mux = &cam_cc, .mux = 0x80 },
	{ .name = "cam_cc_ife_2_clk", .clk_mux = &cam_cc, .mux = 0x2e },
	{ .name = "cam_cc_ife_2_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x32 },
	{ .name = "cam_cc_ife_2_shift_clk", .clk_mux = &cam_cc, .mux = 0x81 },
	{ .name = "cam_cc_ife_lite_ahb_clk", .clk_mux = &cam_cc, .mux = 0x37 },
	{ .name = "cam_cc_ife_lite_clk", .clk_mux = &cam_cc, .mux = 0x33 },
	{ .name = "cam_cc_ife_lite_cphy_rx_clk", .clk_mux = &cam_cc, .mux = 0x36 },
	{ .name = "cam_cc_ife_lite_csid_clk", .clk_mux = &cam_cc, .mux = 0x35 },
	{ .name = "cam_cc_ipe_nps_ahb_clk", .clk_mux = &cam_cc, .mux = 0x1e },
	{ .name = "cam_cc_ipe_nps_clk", .clk_mux = &cam_cc, .mux = 0x1a },
	{ .name = "cam_cc_ipe_nps_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x1f },
	{ .name = "cam_cc_ipe_pps_clk", .clk_mux = &cam_cc, .mux = 0x1c },
	{ .name = "cam_cc_ipe_pps_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x20 },
	{ .name = "cam_cc_ipe_shift_clk", .clk_mux = &cam_cc, .mux = 0x7c },
	{ .name = "cam_cc_jpeg_1_clk", .clk_mux = &cam_cc, .mux = 0x5f },
	{ .name = "cam_cc_jpeg_clk", .clk_mux = &cam_cc, .mux = 0x40 },
	{ .name = "cam_cc_mclk0_clk", .clk_mux = &cam_cc, .mux = 0x1 },
	{ .name = "cam_cc_mclk1_clk", .clk_mux = &cam_cc, .mux = 0x2 },
	{ .name = "cam_cc_mclk2_clk", .clk_mux = &cam_cc, .mux = 0x3 },
	{ .name = "cam_cc_mclk3_clk", .clk_mux = &cam_cc, .mux = 0x4 },
	{ .name = "cam_cc_mclk4_clk", .clk_mux = &cam_cc, .mux = 0x5 },
	{ .name = "cam_cc_mclk5_clk", .clk_mux = &cam_cc, .mux = 0x6 },
	{ .name = "cam_cc_mclk6_clk", .clk_mux = &cam_cc, .mux = 0x7 },
	{ .name = "cam_cc_mclk7_clk", .clk_mux = &cam_cc, .mux = 0x8 },
	{ .name = "cam_cc_qdss_debug_clk", .clk_mux = &cam_cc, .mux = 0x4b },
	{ .name = "cam_cc_qdss_debug_xo_clk", .clk_mux = &cam_cc, .mux = 0x4c },
	{ .name = "cam_cc_sbi_clk", .clk_mux = &cam_cc, .mux = 0x21 },
	{ .name = "cam_cc_sbi_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x23 },
	{ .name = "cam_cc_sbi_shift_clk", .clk_mux = &cam_cc, .mux = 0x7e },
	{ .name = "cam_cc_sfe_0_clk", .clk_mux = &cam_cc, .mux = 0x38 },
	{ .name = "cam_cc_sfe_0_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x3b },
	{ .name = "cam_cc_sfe_0_shift_clk", .clk_mux = &cam_cc, .mux = 0x82 },
	{ .name = "cam_cc_sfe_1_clk", .clk_mux = &cam_cc, .mux = 0x3c },
	{ .name = "cam_cc_sfe_1_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x3f },
	{ .name = "cam_cc_sfe_1_shift_clk", .clk_mux = &cam_cc, .mux = 0x83 },
	{ .name = "cam_cc_sfe_2_clk", .clk_mux = &cam_cc, .mux = 0x76 },
	{ .name = "cam_cc_sfe_2_fast_ahb_clk", .clk_mux = &cam_cc, .mux = 0x7a },
	{ .name = "cam_cc_sfe_2_shift_clk", .clk_mux = &cam_cc, .mux = 0x84 },
	{ .name = "cam_cc_sleep_clk", .clk_mux = &cam_cc, .mux = 0x4f },
	{ .name = "cam_cc_titan_top_shift_clk", .clk_mux = &cam_cc, .mux = 0x85 },
	/* DISPCC Entries */
	{ .name = "disp_cc_mdss_accu_clk", .clk_mux = &disp_cc, .mux = 0x46 },
	{ .name = "disp_cc_mdss_ahb1_clk", .clk_mux = &disp_cc, .mux = 0x37 },
	{ .name = "disp_cc_mdss_ahb_clk", .clk_mux = &disp_cc, .mux = 0x33 },
	{ .name = "disp_cc_mdss_byte0_clk", .clk_mux = &disp_cc, .mux = 0x14 },
	{ .name = "disp_cc_mdss_byte0_intf_clk", .clk_mux = &disp_cc, .mux = 0x15 },
	{ .name = "disp_cc_mdss_byte1_clk", .clk_mux = &disp_cc, .mux = 0x16 },
	{ .name = "disp_cc_mdss_byte1_intf_clk", .clk_mux = &disp_cc, .mux = 0x17 },
	{ .name = "disp_cc_mdss_dptx0_aux_clk", .clk_mux = &disp_cc, .mux = 0x20 },
	{ .name = "disp_cc_mdss_dptx0_crypto_clk", .clk_mux = &disp_cc, .mux = 0x1D },
	{ .name = "disp_cc_mdss_dptx0_link_clk", .clk_mux = &disp_cc, .mux = 0x1A },
	{ .name = "disp_cc_mdss_dptx0_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x1C },
	{ .name = "disp_cc_mdss_dptx0_pixel0_clk", .clk_mux = &disp_cc, .mux = 0x1E },
	{ .name = "disp_cc_mdss_dptx0_pixel1_clk", .clk_mux = &disp_cc, .mux = 0x1F },
	{ .name = "disp_cc_mdss_dptx0_usb_router_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x1B },
	{ .name = "disp_cc_mdss_dptx1_aux_clk", .clk_mux = &disp_cc, .mux = 0x27 },
	{ .name = "disp_cc_mdss_dptx1_crypto_clk", .clk_mux = &disp_cc, .mux = 0x26 },
	{ .name = "disp_cc_mdss_dptx1_link_clk", .clk_mux = &disp_cc, .mux = 0x23 },
	{ .name = "disp_cc_mdss_dptx1_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x25 },
	{ .name = "disp_cc_mdss_dptx1_pixel0_clk", .clk_mux = &disp_cc, .mux = 0x21 },
	{ .name = "disp_cc_mdss_dptx1_pixel1_clk", .clk_mux = &disp_cc, .mux = 0x22 },
	{ .name = "disp_cc_mdss_dptx1_usb_router_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x24 },
	{ .name = "disp_cc_mdss_dptx2_aux_clk", .clk_mux = &disp_cc, .mux = 0x2D },
	{ .name = "disp_cc_mdss_dptx2_crypto_clk", .clk_mux = &disp_cc, .mux = 0x2C },
	{ .name = "disp_cc_mdss_dptx2_link_clk", .clk_mux = &disp_cc, .mux = 0x2A },
	{ .name = "disp_cc_mdss_dptx2_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x2B },
	{ .name = "disp_cc_mdss_dptx2_pixel0_clk", .clk_mux = &disp_cc, .mux = 0x28 },
	{ .name = "disp_cc_mdss_dptx2_pixel1_clk", .clk_mux = &disp_cc, .mux = 0x29 },
	{ .name = "disp_cc_mdss_dptx3_aux_clk", .clk_mux = &disp_cc, .mux = 0x31 },
	{ .name = "disp_cc_mdss_dptx3_crypto_clk", .clk_mux = &disp_cc, .mux = 0x32 },
	{ .name = "disp_cc_mdss_dptx3_link_clk", .clk_mux = &disp_cc, .mux = 0x2F },
	{ .name = "disp_cc_mdss_dptx3_link_intf_clk", .clk_mux = &disp_cc, .mux = 0x30 },
	{ .name = "disp_cc_mdss_dptx3_pixel0_clk", .clk_mux = &disp_cc, .mux = 0x2E },
	{ .name = "disp_cc_mdss_esc0_clk", .clk_mux = &disp_cc, .mux = 0x18 },
	{ .name = "disp_cc_mdss_esc1_clk", .clk_mux = &disp_cc, .mux = 0x19 },
	{ .name = "disp_cc_mdss_mdp1_clk", .clk_mux = &disp_cc, .mux = 0x34 },
	{ .name = "disp_cc_mdss_mdp_clk", .clk_mux = &disp_cc, .mux = 0x11 },
	{ .name = "disp_cc_mdss_mdp_lut1_clk", .clk_mux = &disp_cc, .mux = 0x35 },
	{ .name = "disp_cc_mdss_mdp_lut_clk", .clk_mux = &disp_cc, .mux = 0x12 },
	{ .name = "disp_cc_mdss_non_gdsc_ahb_clk", .clk_mux = &disp_cc, .mux = 0x38 },
	{ .name = "disp_cc_mdss_pclk0_clk", .clk_mux = &disp_cc, .mux = 0xF },
	{ .name = "disp_cc_mdss_pclk1_clk", .clk_mux = &disp_cc, .mux = 0x10 },
	{ .name = "disp_cc_mdss_rscc_ahb_clk", .clk_mux = &disp_cc, .mux = 0x3A },
	{ .name = "disp_cc_mdss_rscc_vsync_clk", .clk_mux = &disp_cc, .mux = 0x39 },
	{ .name = "disp_cc_mdss_vsync1_clk", .clk_mux = &disp_cc, .mux = 0x36 },
	{ .name = "disp_cc_mdss_vsync_clk", .clk_mux = &disp_cc, .mux = 0x13 },
	{ .name = "disp_cc_sleep_clk", .clk_mux = &disp_cc, .mux = 0x47 },
	{ .name = "disp_cc_xo_clk", .clk_mux = &disp_cc, .mux = 0x45 },
	/* GPUCC entries */
	{ .name = "gpu_cc_ahb_clk", .clk_mux = &gpu_cc, .mux = 0x18 },
	{ .name = "gpu_cc_crc_ahb_clk", .clk_mux = &gpu_cc, .mux = 0x19 },
	{ .name = "gpu_cc_cx_ff_clk", .clk_mux = &gpu_cc, .mux = 0x22 },
	{ .name = "gpu_cc_cx_gmu_clk", .clk_mux = &gpu_cc, .mux = 0x1f },
	{ .name = "gpu_cc_cxo_aon_clk", .clk_mux = &gpu_cc, .mux = 0xc },
	{ .name = "gpu_cc_cxo_clk", .clk_mux = &gpu_cc, .mux = 0x20 },
	{ .name = "gpu_cc_demet_clk", .clk_mux = &gpu_cc, .mux = 0xe },
	{ .name = "gpu_cc_freq_measure_clk", .clk_mux = &gpu_cc, .mux = 0xd },
	{ .name = "gpu_cc_gx_ff_clk", .clk_mux = &gpu_cc, .mux = 0x14 },
	{ .name = "gpu_cc_gx_gfx3d_rdvm_clk", .clk_mux = &gpu_cc, .mux = 0x16 },
	{ .name = "gpu_cc_gx_gmu_clk", .clk_mux = &gpu_cc, .mux = 0x13 },
	{ .name = "gpu_cc_gx_vsense_clk", .clk_mux = &gpu_cc, .mux = 0x10 },
	{ .name = "gpu_cc_hub_aon_clk", .clk_mux = &gpu_cc, .mux = 0x31 },
	{ .name = "gpu_cc_hub_cx_int_clk", .clk_mux = &gpu_cc, .mux = 0x21 },
	{ .name = "gpu_cc_memnoc_gfx_clk", .clk_mux = &gpu_cc, .mux = 0x23 },
	{ .name = "gpu_cc_mnd1x_gfx3d_clk", .clk_mux = &gpu_cc, .mux = 0x2d },
	{ .name = "gpu_cc_sleep_clk", .clk_mux = &gpu_cc, .mux = 0x1d },
	{ .name = "measure_only_gpu_cc_cx_gfx3d_clk", .clk_mux = &gpu_cc, .mux = 0x28 },
	{ .name = "measure_only_gpu_cc_cx_gfx3d_slv_clk", .clk_mux = &gpu_cc, .mux = 0x21 },
	{ .name = "measure_only_gpu_cc_gx_gfx3d_clk", .clk_mux = &gpu_cc, .mux = 0xf },
	/* VIDEOCC Entries */
	{ .name = "video_cc_ahb_clk", .clk_mux = &video_cc, .mux = 0x7 },
	{ .name = "video_cc_mvs0_clk", .clk_mux = &video_cc, .mux = 0x3 },
	{ .name = "video_cc_mvs0c_clk", .clk_mux = &video_cc, .mux = 0x1 },
	{ .name = "video_cc_mvs1_clk", .clk_mux = &video_cc, .mux = 0x5 },
	{ .name = "video_cc_mvs1c_clk", .clk_mux = &video_cc, .mux = 0x9 },
	{ .name = "video_cc_sleep_clk", .clk_mux = &video_cc, .mux = 0xc },
	{ .name = "video_cc_xo_clk", .clk_mux = &video_cc, .mux = 0xb },
	{ }
};

struct debugcc_platform sm8650_debugcc = {
	.name = "sm8650",
	.clocks = sm8650_clocks,
};
